### ISSUE TITLE
Add ability to fill in Study PI name and ORCID from logged-in user details

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#108]
Currently the app makes the same assumption as the submission portal that the person creating the study/submission is _not_ necessarily the same person as the study PI. I _think_ that should still be the assumption, but we should also add a button or some other affordance to the interface that allows the PI name and ORCID inputs to be filled in with the logged-in user's information if they choose to do so. 

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/102547565/fb7a7d95-d6e2-40b6-a3f7-513ec89a5d89)

Note: at the moment we don't collect email addresses from ORCID, so we wouldn't be able to fill that one in automatically yet.

**Comment by eecavanna** [comment]
Here's one UI option.

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/23ec65f6-f81c-4a53-93bc-5c091f61f18d)

In this example, each field has its own affordance. I assume most users that use it for one field would want to use it for all of those fields.
