### ISSUE TITLE
Publish Android app to Google Play Store (for beta testing)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#131]
This ticket is the Android counterpart to https://github.com/microbiomedata/nmdc-field-notes/issues/114.

The task is to publish an APK of our app to whatever service Google provides for beta testing apps.

References:
- https://support.google.com/googleplay/android-developer/answer/9845334?hl=en

**Comment by eecavanna** [comment]
The iOS workload has grown this sprint, so I'm moving this Android-specific ticket to the next sprint.

**Comment by eecavanna** [comment]
@pkalita-lbl worked with IT to get each of us added to the Lab's Google Play Console account. That got us closer to completing this task.

**Comment by ssarrafan** [comment]
Can this be moved to the next sprint @eecavanna ?

**Comment by eecavanna** [comment]
@pkalita-lbl and I will be pairing on this tomorrow (Friday) morning, as our hackathon task.

**Comment by eecavanna** [comment]
I'd prefer it remain in the current sprint and I move it (or close it) at the end of the day tomorrow.

**Comment by eecavanna** [comment]
The Android app is now technically available to me and @pkalita-lbl via the Google Play Store 🙌 , which one could argue does what the issue title says; but the "Definition of Done" I had in mind when creating this ticket was:
- [ ] Make it so all our Android beta testers can install the beta version of the app via the Google Play Store

With that in mind, I'll leave this open and move it to the next sprint.

**Comment by pkalita-lbl** [comment]
Things we need before we can complete the "Set up your app" section of the Play Console dashboard:

* A [privacy policy](https://support.google.com/googleplay/android-developer/answer/9859455?hl=en#privacy_policy). This will allow us to check off the "Set privacy policy" and "Data safety" checkboxes.
* Decide whether we want a "Government" label on our store listing. If yes, there may be more information to provide. If no, we just need to select "No" in the "Government apps" section.
* A [Feature graphic](https://support.google.com/googleplay/android-developer/answer/9866151#zippy=%2Cfeature-graphic). The docs have a number of suggestions, but the overall impression is that this is _not_ just a logo or screenshot image. The engagement team might have suggestions, but this may be something new we have to come up with.
* [Screenshots](https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots). It appears that we need 2-8 phone screenshots and and "up to 8" (does that include 0?) screenshots of both 7-inch tablets and 10-inch tablets.

**Comment by ssarrafan** [comment]
Looks like a template that may be helpful for privacy policy: https://www.lbl.gov/privacy-policy/

**Comment by pkalita-lbl** [comment]
Closing this issue in favor of individual issues for remaining tasks:

* #194 
* #195 
* #196
