### ISSUE TITLE
Implement in-app tours (screen-specific)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#133]
#### Tasks

- [x] Implement in-app tours
  - Content will be produced as part of this related issue: https://github.com/microbiomedata/nmdc-field-notes/issues/63
  - I am currently planning to use the [reactour](https://www.npmjs.com/package/reactour) library
- [x] Add option on "Settings" screen to reset all the `isTourTaken` statuses, so tours appear to the user again even if they have already gone through them (this will allow users to re-take tours)
  - This aspect of the task was originally represented by this related issue (closed in favor of this one—i.e. the aforementioned functionality is not implemented yet): https://github.com/microbiomedata/nmdc-field-notes/issues/88

**Comment by eecavanna** [comment]
Here's a link to a Slack message containing an example portion of an in-app tour:

https://nmdc-group.slack.com/archives/C060MQ7BA9K/p1721630187832319

**Comment by ssarrafan** [comment]
@eecavanna is this still being actively worked on?  Should I move it to the next sprint?

**Comment by eecavanna** [comment]
I am planning to work on it today, but not finish it today. I'll move it to the next sprint already.
