### ISSUE TITLE
Fill out Test Information section in App Store Connect

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#141]
In order to start external beta testing we need to:

- Fill out the Test Information section in App Store Connect
- Submit to Apple for review

Here is the information we need:

1. **Beta App Description**: Provide a description of your app that highlights its features and functionality.
2. **Feedback Email**: TestFlight Beta Testers can send feedback to this email address. It will also appear as the reply-to address for TestFlight invitation emails.
3. **Marketing URL**: A URL with information about the app you are adding. This will be visible to testers in the TestFlight app.
4. **Privacy Policy URL**: A URL that links to your company’s privacy policy. Privacy policies are recommended for all apps that collect user or device related data or as otherwise required by law.
5. Contact Information
  a. **First Name**
  b. **Last Name**
  c. **Phone number**
  d. **Email**
6. **Sign-in Information**: This is a user name and password we can use to sign in to your app, so we can review all of its features. If users sign in using social media, provide information for an account we can use. Credentials must be valid and active for duration of review.
7. **Review Notes**: Additional information about your app that can help during the review process. Do not include demo account details. Review notes can’t exceed 4000 characters.
8. **License Agreement**

**Comment by eecavanna** [comment]
For some additional context, here's a screenshot (composite) showing the "Test Information" form.

![image](https://github.com/user-attachments/assets/fbe5c3e2-11c2-48eb-82df-5db9dc694afd)

**Comment by eecavanna** [comment]
> **6. Sign-in Information**

Hi @emileyfadrosh, assuming you are working on generating content for this form, you can skip doing so for the "Sign-in Information" fields.

For those fields, I will: (a) create a [disposable email address](https://inboxes.com/), (b) create an ORCID account using that email address, and then (c) put the username and password of that ORCID account into the "Sign-in Information" fields.

Steps (a) and (b) are the same things I did to create the "Jean Orcid" user that appeared in the demo video a few months ago.

**Comment by eecavanna** [comment]
Here's what I propose for an initial submission:

1. **Beta App Description**: 
   > NMDC Field Notes is an iOS/iPadOS app microbiome researchers can use to record metadata about the biosamples they collect while they are working in the field. It is a mobile alternative to the browser-based NMDC Submission Portal web app, designed specifically to streamline the process of documenting metadata at the time of biosample collection. Its features (all of which were designed in collaboration with microbiome researchers) include: ORCID login, entry of study and biosample metadata, one-tap entry of user information, geographical coordinates, and dates, user interface forms that are dynamically generated from a LinkML schema, and automatic syncing of study and biosamples metadata with the NMDC Submission Portal.
2. **Feedback Email**: `support+fieldnotes@mic........ata.org` (partially redacted here to avoid spam)
3. **Marketing URL**: `https://microbiomedata.org/field-notes/`
4. **Privacy Policy URL**: `https://www.lbl.gov/terms-and-conditions/web-privacy-notice/`
5. Contact Information
  a. **First Name**: `NMDC`
  b. **Last Name**: `Support`
  c. **Phone number**: _(None)_
  d. **Email**: `support+fieldnotes@mic........ata.org` (partially redacted here to avoid spam)
6. **Sign-in Information**: `ORCID username: {REDACTED}, ORCID password: {REDACTED}`
7. **Review Notes**: 
   > Thanks for helping us test the iOS/iPadOS version of NMDC Field Notes.
   >
   > If you encounter an issue or want to request a feature, please file a ticket in our GitHub repository, at: https://github.com/microbiomedata/nmdc-field-notes/issues
   >
   > If you don't have a GitHub account or you don't want to file a ticket on GitHub, you can send us an email at our "Feedback Email" address.
   >
   > Finally, once you've explored the app, please summarize your feedback by filling out our standard beta test survey: {URL_REDACTED}
8. **License Agreement**: _(None)_

**Comment by eecavanna** [comment]
I misunderstood the "Review Notes" field, as I wrote the above blurb with our beta testers—instead of Apple's reviewer—as my target audience. Oops!

**Comment by eecavanna** [comment]
I submitted the form with the above content (for the most part) in it and Apple approved of it. So, I'll close this ticket.

I'll create a separate ticket about documenting our privacy policy and hosting it at some URL.
