### ISSUE TITLE
Sample editing needs to take `any_of` into account when determining input style

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#143]
Currently in the `SoilInterface` class the `env_broad_scale` slot has an `any_of` range union:

```
{
  "name": "env_broad_scale",
  ...
  "any_of": [
    {
      "range": "EnvBroadScaleSoilEnum"
    },
    {
      "range": "string"
    }
  ]
}
```

This is interpreted by DataHarmonizer in the desktop submission portal to mean: present the options from `EnvBroadScaleSoilEnum` as dropdown options, but allow the user to enter freeform text as well. 

I don't know how easy that exact behavior will be to replicate with Ionic components. At the very least we should probably fallback to presenting a select box instead of a text input box in this case.

**Comment by mslarae13** [comment]
> select box instead of a text input box in this case.

yes. Ideally people aren't putting in their own text :)

**Comment by pkalita-lbl** [comment]
Duplicate of #176
