### ISSUE TITLE
Implement version number management

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#147]
On the "Settings" tab, the app displays its version number; e.g. `0.0.1`.

So far, we have not been incrementing or otherwise changing that version number (defined within `package.json`) as we have been building new versions of the app.

Now that we are nearing the point of having people beta test the app, I want to begin incrementing or otherwise changing the app's version number when we create new "builds" (maybe "builds" is not the right term here for what I'm thinking of).

The task here is to implement, and document, a version number management strategy.

Consider:
- Google Play version management
- Apple App Store version management (e.g. TestFlight has the concept of a build number, which is distinct from the version number)
- NPM commands
- GitHub Actions
- Whether Ionic provides some facilities for this

**Comment by ssarrafan** [comment]
Removing from sprint.  Nobody is assigned this issue yet.  Please add to future sprint if someone will be working on it.

**Comment by eecavanna** [comment]
@pkalita-lbl implemented this as part of a recent PR (merged): https://github.com/microbiomedata/nmdc-field-notes/pull/149/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R247-R255

I will close this ticket.
