### ISSUE TITLE
Document process of creating and distributing new beta builds

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#148]
Document process of creating and distributing new beta builds (iOS).

---

Here's a starting point:

1. Given how my Xcode is currently set up, here's roughly how I currently create a new "build" (some of this may be unnecessary, such as launching the simulator):
2. At the CLI:
   1. Check out the `main` branch, run `$ git pull`, and ensure my local file tree contains no changes (relative to the main branch)
   2. Run `$ npm install`
   3. Run `$ npm run sim.ios` and choose the iPhone 15 (I think other iPhone/iPad versions would work, too)
3. After confirming the app starts up in the simulator, close the simulator
4. In Xcode:
   1. "[Create an archive of the app](https://developer.apple.com/documentation/xcode/distributing-your-app-for-beta-testing-and-releases#Create-an-archive-of-your-app)" by clicking (in the toolbar) `Product` > `Archive`
   2. "[Select the method of distribution](https://developer.apple.com/documentation/xcode/distributing-your-app-for-beta-testing-and-releases#Select-a-method-for-distribution)" to be TestFlight & App Store
   3. Click the "Validate App" button to validate the build with respect to App Store Connect
   4. Click the "Distribute App" button to upload the build to App Store Connect
5. On App Store Connect:
   1. Go to `Apps` > `NMDC Field Notes` > `TestFlight`
   2. Under "iOS Builds," find the newly-uploaded build (in the table of all builds)
   3. If it says "Missing Compliance", click "Manage", select "None of the algorithms mentioned above", and click "Save". The words "Ready to Submit" will take the place of the "Missing Compliance" message.
   4. In the sidebar, click on one of the tester groups (e.g. NMDC iOS Developers)
   5. Add the newly-uploaded build to this group (by clicking the `+` button next to "Builds"). At this point the people in that tester group will receive an email telling them that a new build is available to test (and that they can get it by opening the TestFlight app).
   6. Repeat the previous two substeps for the other tester groups.

**Comment by pkalita-lbl** [comment]
I'm slightly expanding the scope of this issue to cover a broader beta release process that includes:

* The "administrative" stuff (updating the `version` field in `package.json`, creating Git tags, creating GitHub releases, etc)
* Building and publishing the iOS version (what Eric documented above)
* Building and publishing the Android version (what I've been doing informally at odd intervals)
