### ISSUE TITLE
Ensure theme color palette is consistent with NMDC branding guidelines

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#15]
In PR https://github.com/microbiomedata/nmdc-field-notes/pull/13, I merged a branch that overrode Ionic's default `variables.css` file so that the app's color palette would be consistent with my understanding of the NMDC branding guidelines.

My understanding is based on:
- A document on Google Drive named "NMDC Branding Notes"
- A [colors.cs](https://github.com/microbiomedata/nmdc-server/blob/main/web/src/colors.js) file in the `nmdc-server` repository

Based on that understanding, I filled out the [Ionic color generator](https://ionicframework.com/docs/theming/color-generator) as follows:
- Primary: `#4f3B80`
- Secondary: `#00AAE7`
- Tertiary: `#E88320`
- Success: `#388E3C`
- Warning: `#E88320`
- Danger: `#ED5338`
- Light: `#F4F5F8`
- Medium: `#92949C`
- Dark: `#222428`

The generator produced a block of CSS, which I copy/pasted into the [variables.css](https://github.com/microbiomedata/nmdc-field-notes/pull/13/commits/e530cf8c63c7d0058a1a3e67b5b21de50504dfa0#diff-f1989d451fa0b0025c8bd7d3397e0a2db12b91af73a72ccbbbf0042222afcb4d) file in this repo.

A teammate noticed the NMDC branding guidelines said that the NMDC Submission Portal is illustrated with blue hues" and, so, he [posed the question](https://github.com/microbiomedata/nmdc-field-notes/issues/14#issuecomment-1912332062):

> Since the Field Notes App is primarily linked to the submission portal, maybe we can switch primary vs secondary so that the App is predominantly blue?

I looked at the [submission portal](https://data.microbiomedata.org/submission/home) and thought it was using purple as the primary color, not blue.

---

I'm creating this ticket to represent the task of reconciling people's understandings of the NMDC branding guidelines, with the colors in use on existing NMDC products, and with the team's vision for the NMDC Field Notes app.

**Comment by simroux** [comment]
Just a note to confirm that the desired look for MVP is to have the primary color as blue to match the submission portal guidelines :-)

**Comment by eecavanna** [comment]
### Purple as primary color

Here are screenshots of what the current welcome page would look like with the primary color set to **purple**.

||iOS|Android|
|--|--|--|
|Light|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/7c9e4f67-e4ee-413b-bf9d-1286eb479f57" height="400" />|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/223a9480-2a53-436a-922f-7c9edd5ff95d" height="400" />|
|Dark|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/9e60438c-85ed-474f-974d-55fb81889923" height="400" />|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/a91b480c-3c21-4f6a-83e4-6d46a08f41c4" height="400" />|

### Blue as primary color

Here are screenshots of what the current welcome page would look like with the primary color set to **blue**.

||iOS|Android|
|--|--|--|
|Light|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/a606b967-a647-422b-9b0c-cea683dde4ca" height="400" />|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/e7221cbd-a217-47fc-af68-cbf89eca5c75" height="400" />|
|Dark|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/adb485e4-234c-47c9-a0cb-aac1d17c2613" height="400" />|<img src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/e7dbeab3-d030-4c58-b32b-0697746bb4b7" height="400" />|

### Data and submission portal

Here are screenshots of the data and submission portal home pages.

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/dfe5e41d-3fb8-4169-a884-47adbfc679fc)

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/11ca3c67-0b8a-410e-9e8b-c9051713a2ea)

**Comment by simroux** [comment]
Looping back to this question, and following on some Slack discussion (https://nmdc-group.slack.com/archives/C060MQ7BA9K/p1711036266225529), the ask is for the css to have **blue as the primary color** for the video generated for GSP/ECR (so should be changed now).
