### ISSUE TITLE
Legal: Confirm we have permission to use GSA Field Ethics and Sampling Checklist image

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#158]
In PR #152, @yxu-lanl _temporarily_ incorporated the following image into the checklist screen:

<img src="https://github.com/user-attachments/assets/a3cebb4e-a745-4aa5-8dd6-b148d8565b74" alt="GSA Field Ethics and Sampling Checklist" width="600" />

While reviewing that PR, @pkalita-lbl pointed out that the image was created by someone else and he wanted to confirm we have received their permission to use that image in this way.

I am creating this ticket to represent the task of obtaining that permission (whether _actively_—by asking someone at the GSA—or _passively_—by identifying a "license" document that grants that permission to us/people).

**Comment by pkalita-lbl** [comment]
I think the copy of our field guide section is solid without this graphic. Closing.
