### ISSUE TITLE
TestFlight: Separate NMDC team members and other people into distinct groups

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#162]
### Background

Currently, we have one group of "External Testers," which is named "Other People." This group consists of both NMDC team members and other people (e.g. researchers that are not NMDC team members). As long as they are all in a single group, we do not have the option to make certain builds available to NMDC team members without also making those same builds available to other people—which is something we _may_ eventually want to do (right now, I don't).

### Task

I'm creating this ticket to represent the task of separating those two sets of people out into two different groups in the "External Testers" category on TestFlight.

### Appendix

On August 22, I created a new group, but TestFlight would not allow me to add any builds to it. That's why I resorted to just adding everyone to our one group that already existed. In case this was a temporary TestFlight bug, I recommend trying again—in a few days—to create a new group and add a build to it.

**Comment by pkalita-lbl** [comment]
We've decided we don't need the level of release granularity that separate groups would provide. Closing.
