### ISSUE TITLE
Allow for dropdowns when entering IDs for the MIxS environmental triad

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-field-notes#164]
When I used the app it looks like it wants you to type in the identifier-label tuple consistent with MIxS syntax, e,g "tropical biome [ENVO:nnnnnnn]". I think this is hard enough on a normal web, but incredibly hard on an iPhone.

We should just offer the user dropdowns here. These would be contextual, so FN would need access to lookup tables of `(extension, slot) -> {terms}`. The value set squad is looking at these cc @mslarae13. I think it could be useful if we could organize things such that we get example value sets of the environment slots for soil sooner, even if imperfect, and then iterate on this. I think it's better to give the beta user a selection set that is too small than to force them to do some awkward text editing of mixs syntax.

**Comment by mslarae13** [comment]
The field notes squad could work on the drop downs now with the manually curated list of PVs we identified for soil env triad.
Then it would just be a matter of updating the PVs when env triad squad finishes its work.
