### ISSUE TITLE
Water schema is missing from Guide

### ISSUE THREAD

**Issue by cpavloud** [microbiomedata/nmdc-field-notes#170]
### Bug details

The water checklist is missing from the Guide, although it is included in the "Field Visibility" section. 

### Steps to reproduce

1. Download and install [org.microbiomedata.fieldnotes-v0.1.0-build.4.apk](https://github.com/microbiomedata/nmdc-field-notes/releases/download/v0.1.0/org.microbiomedata.fieldnotes-v0.1.0-build.4.apk)
2. Launch app
3. Tap "View the checklist"

### Device type

Android

### Operating system version

13

**Comment by pkalita-lbl** [comment]
Thanks for submitting this bug report! We have fixed the issue, and the fix will be available in the next build. Currently we expect to release a new build in about a week or two.
