### ISSUE TITLE
Account for changes to `packageName` field on backend

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#177]
Part of the proposed changes for https://github.com/microbiomedata/nmdc-server/issues/1367 is changing the `packageName` field of a submission object from a string to an array of strings. This will break certain things in the app. We need to sort out:

1. How the app will handle this change. What would it look like to fully support creating, displaying, and updating studies that use multiple environment templates? Is it simpler to continue to only support a single environment template in the app?
2. How will we coordinate releasing app changes along with the backend changes? Is it possible to update the app to work with _either_ a string or array of strings in `packagename` and release that change _ahead_ of the backend changes?

**Comment by pkalita-lbl** [comment]
Cross-linking the proposed backend changes here: https://github.com/microbiomedata/nmdc-server/pull/1372

**Comment by ssarrafan** [comment]
@pkalita-lbl who should this one be assigned to?

**Comment by pkalita-lbl** [comment]
The work on this is paused until https://github.com/microbiomedata/nmdc-server/issues/1367 is resolved. I believe that work is paused until after the Berkeley refactor roll-out is complete. Moving to next sprint.

**Comment by ssarrafan** [comment]
Berkeley was rolled out so can this be closed @pkalita-lbl ?

**Comment by pkalita-lbl** [comment]
This cannot be closed.

It doesn't really have anything to do with Berkeley. The gating factor is the PR for https://github.com/microbiomedata/nmdc-server/issues/1367 being merged in.

**Comment by pkalita-lbl** [comment]
Still paused waiting for https://github.com/microbiomedata/nmdc-server/issues/1367. Moving to next sprint.

**Comment by pkalita-lbl** [comment]
Still paused waiting for https://github.com/microbiomedata/nmdc-server/issues/1367. Moving to next sprint.

**Comment by ssarrafan** [comment]
@pkalita-lbl update from @marySalvi  on issue #1367: 
_Yes, this will be ready for the December release. This has been blocked by the bug in the runtime code (my runtime code). I have made good progress towards a resolution and am hoping to wrap this up shortly._

Based on this can I move this to the next sprint?

**Comment by pkalita-lbl** [comment]
I moved it.
