### ISSUE TITLE
Wrong build number displayed in app for build `0.1.0 (5)`

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#182]
### Bug summary

Wrong build number displayed in app for build `0.1.0 (5)`

### Bug details

After installing build `0.1.0 (5)`, the Settings page still displays `0.1.0 (4)` in the Version field. It should say `0.1.0 (5)`.

### App version

0.1.0 (5)

### Device type

None

### Operating system version

Confirmed on both iOS and Android

**Comment by pkalita-lbl** [comment]
Currently we have in our `package.json` `scripts`:

```json
    "prerelease": "vitest run && npm run build.native",
    "release": "./scripts/release.sh",
```

I can't remember the rationale for having `npm run build.native` as part of the `prerelease` step. It seems like it would make more sense to be in `postrelease`. That's just my gut reaction, but it needs a closer look.

**Comment by ssarrafan** [comment]
@pkalita-lbl who should this be assigned to?

**Comment by pkalita-lbl** [comment]
It's kind of up-for-grabs for any of the Field Notes developers. But if you're looking to have all the current sprint issues assigned to someone I'll take it.
