### ISSUE TITLE
In analysis/data type field of a Sample, input allows multi-select list but decorates with radio buttons.

### ISSUE THREAD

**Issue by sierra-moxon** [microbiomedata/nmdc-field-notes#185]
### Bug summary

In analysis/data type field of a Sample, input allows multi-select list but decorates with radio buttons.

### Bug details

I tend to expect checkboxes with multi-select fields vs. radio buttons that tell me to pick one of the list members. 

### Steps to reproduce

1. Launch app
2. Create a study
3. Start a new Sample
4. select "Template: plant-associated"
5. touch `analysis/data type` required field

### App version

erg, not sure where to find this

### Device type

Apple

### Operating system version

iOS 17.6.1

**Comment by pkalita-lbl** [comment]
@sierra-moxon just to confirm you saw something like this?

![image](https://github.com/user-attachments/assets/e080e5ca-44fb-4caf-b9ab-218dc3a3e62d)

**Comment by sierra-moxon** [comment]
yep that is what I am talking about.

**Comment by mslarae13** [comment]
Square = multiselect
Circle = pick 1 in my mind. So I agree, but we will probably move this slot down / out of the FIELD sampling priority. 
#150

**Comment by pkalita-lbl** [comment]
Circular checkbox are an iOS standard. I think we'll probably not want to deviate from that. Closing.
