### ISSUE TITLE
Once I dismiss the "Too many fields" bar, I can't get it back

### ISSUE THREAD

**Issue by sierra-moxon** [microbiomedata/nmdc-field-notes#191]
### Bug summary

In filling out fields for a "sample", if I dismiss the "Too many fields" bar on the top, I can't seem to figure out how to get it back

### Bug details

Things I tried:
- dismiss the "Too many fields" bar
- go back to my Study page
- click on my sample again - still missing the "Too many fields" bar
- tried making a "new" sample - still missing the "Too many fields bar
- went back to my "Settings" window and clicked "Reset tours" - but that just got me back the white windows covering my screen

I kinda dismissed it just to try out what that would do, but then got myself into a pickle. :) 

### Device type

Apple

### Operating system version

iOS 17.6.1

**Comment by pkalita-lbl** [comment]
> went back to my "Settings" window and clicked "Reset tours" 

You were so close. Settings -> Field Visibility is what you were looking for.

**Comment by pkalita-lbl** [comment]
Duplicate of #150 

I'm marking this a duplicate of another issue so that GitHub links them together. In reality, the field visibility functionality of the app is going to get reworked a lot with #150 and once that's completed a lot of this type of confusion should go away.
