### ISSUE TITLE
Determine privacy policy and provide to app stores

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#194]
This task is to draft a privacy policy document and provide a link to that document to the Apple and Google stores. This may provide a starting point for such a document: https://www.lbl.gov/privacy-policy/ 

@eecavanna suggested we could look at the other LBNL apps in App Store Connect to reverse engineer what they did.

We should also probably have the document reviewed by LBNL IPO.

**Comment by simroux** [comment]
One such app is https://mygreencar.com, but their privacy policy may not be reverse-engineerable - https://mygreencar.com/privacy-policy/

**Comment by pkalita-lbl** [comment]
Duplicate of #144
