### ISSUE TITLE
Release new beta build before current one expires

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#203]
The current build expires in about 22 days (from November 25; so, in mid-December).

**Comment by ssarrafan** [comment]
@eecavanna did this get updated this week?

**Comment by eecavanna** [comment]
No, we did not create a new build of the app this week. I'll move this to the next sprint. We have until mid-December to do this.

**Comment by pkalita-lbl** [comment]
Build `0.1.0 (6)` was released today.
