### ISSUE TITLE
Add deep linking into iOS and Android apps

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#28]
With #26 the basic mechanisms for authentication are in place. I mainly tested using the web version locally (there is an issue with how the web version works on GitHub pages, see #27). The only missing piece for completing the login flow on iOS and Android versions is configuring them to handle links to `https://fieldnotes.microbiomedata.org` so that the app can collect the token provided by `nmdc-server`. Capacitor has a [handy guide](https://capacitorjs.com/docs/guides/deep-links) to follow.

**Comment by eecavanna** [comment]
I'll start looking into the Apple/iOS part of this today.

**Comment by eecavanna** [comment]
I immediately ran into a blocker: I don't have permission to register an App ID. I have contacted the "Account Holder" of our lab Apple Developer account to see if he can help.

In the meantime, here are some related links:
- Registering an app ID: https://developer.apple.com/help/account/manage-identifiers/register-an-app-id/
- App capabilities: https://developer.apple.com/documentation/xcode/adding-capabilities-to-your-app/
- "Identifiers" list: https://developer.apple.com/account/resources/identifiers/list

**Comment by eecavanna** [comment]
Re-opening.

Current status:

- [x] Configure web server 
  - Done via PR #39
- [x] Configure Android app
  - Done via PR #40...
  - ...although I may have to provide someone with the Keystore file I generated
- [ ] Configure iOS app
  - TODO: https://capacitorjs.com/docs/guides/deep-links#add-associated-domain
