### ISSUE TITLE
Implement individual sample page

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#46]
When a user taps on an individual sample listed on a study page (https://github.com/microbiomedata/nmdc-field-notes/issues/30), they should be taken to a sample page. The mockups don't appear to spec out much in particular for this page. My general thought is that this could be a hybrid view/edit page. Since there are potentially a lot of metadata fields for each sample I'm not sure a monolithic form with an input for each field presented all at once will be optimal. 

Rather, I could envision a page that displays each field like a "view" page, but tapping on a field brings up an edit overlay for that single field. The overlay could also present descriptive information from the schema (see also https://github.com/microbiomedata/nmdc-server/issues/1166) similar to the help sidebar in the desktop submission portal. The main view should also give an indication of fields that don't validate. A very rough sketch:

![Image](https://github.com/microbiomedata/nmdc-field-notes/assets/102547565/e92d847b-014a-48f9-97ba-0eee8af0d102)

**Comment by simroux** [comment]
I agree with the main idea (page with a lot of fields displayed in "view" mode, users click on individual fields to edit). May need some UI cue for the latter, e.g. a "..." to click on to edit.
Adding the help on the edit page would be really great, and I also agree that this would be a good place for a button like "autofill" or "scan barcode".

So overall, the design you describe sounds great, and covers all the standard use cases I can think of at this point :-)

**Comment by eecavanna** [comment]
I agree with @simroux. Looks good!

**Comment by ljohnson09** [comment]
I like the (!) you included in sample 5, we had discussed some way of denoting "required/recommended/optional" for NMDC standards, so that might be a good way to format it w/ different symbols or colors there?

**Comment by pkalita-lbl** [comment]
Yeah without going too overboard we could probably use iconography to distinguish at the list level between: a required value is missing, a recommended value is missing, something else (value doesn't match pattern, numeric value out of range, etc). And of course the overlay could provide the full details on the issue. At least that's what I had been thinking.
