### ISSUE TITLE
Design and implement tutorial screens

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#48]
- [ ] Design tutorial (conceptually)
- [ ] Design and implement tutorial screens

In [this issue](https://github.com/microbiomedata/issues/issues/562), a team member pointed out that Ionic [recommends](https://ionicframework.com/docs/react/slides) the use of a library called `Swiper.js`.

**Comment by ssarrafan** [comment]
@ljohnson09 said she can draft something so I will assign to Leah for the next sprint.

**Comment by eecavanna** [comment]
PR #62 will resolve the (preliminary) implementation piece of this ticket. 

The tutorial content will be stored in mostly-Markdown files (technically, JavaScript files that contain Markdown sections) and can be refined/edited in separate PRs.
