### ISSUE TITLE
Implement URL Listener to map universal link to in-app route

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#52]
From the Capacitor [docs](https://capacitorjs.com/docs/guides/deep-links#deep-link-routing-using-the-capacitor-app-api):

> When the native app is opened after a deep link is clicked, the mobile OS doesn't automatically know where to route the user. This must be implemented within the app itself using the Capacitor [App API](https://capacitorjs.com/docs/apis/app) on app startup.

Oops! I did not implement anything in the app to consume the universal link, once the OS launches the app in response to someone tapping on a universal link in their mobile web browser.

Here's documentation about doing so for a React app: https://capacitorjs.com/docs/guides/deep-links#react

**Comment by eecavanna** [comment]
Moving to next sprint because I will not have finished testing it by Friday noon.

**Comment by eecavanna** [comment]
I'm going to remove this from the current sprint as I do not expect to finish testing it by the end of the week.

**Comment by eecavanna** [comment]
I'll be working on this ticket on Thursday, 5/30.

**Comment by eecavanna** [comment]
I used an online tool (https://branch.io/resources/aasa-validator/) to check whether our web server is properly configured for iOS Universal Links.

> The AASA Validator, formerly the Universal Links Validator, can be used to test if your website is properly configured for Universal Links. We’ll test your domain against Apple’s requirements for hosting your Apple App Site Association file along with what we have seen in production that leads to a successful implementation of Universal Links.

The tool says it is properly configured.

<img width="1197" alt="image" src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/49a8b194-d33c-443a-89a2-67a902188f6c">

**Comment by eecavanna** [comment]
I confirmed, in Xcode, that the "Associated Domains" section contains what I expect. While confirming that, I noticed the bundle identifier in Xcode contains what I think is a generic/default Ionic value.

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/6b5ae542-21f6-429e-96ae-be421c4a112b)

I wonder whether this mismatch is coming into play here.

**Comment by eecavanna** [comment]
I found a "Technotes" note on Apple's website called "TN3155: Debugging universal links`. I'm skimming it now.

https://developer.apple.com/documentation/technotes/tn3155-debugging-universal-links

**Comment by ssarrafan** [comment]
@eecavanna does this issue need to continue for the next sprint?  Also, is "in review" the correct status?

**Comment by eecavanna** [comment]
I expect this issue to be closed by the end of the day. "In Review" is accurate.
