### ISSUE TITLE
Finalize content for in-app tutorial

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#63]
This ticket represents the task of finalizing the tutorial content (e.g. standardizing punctuation, addressing typos—if any).

The content is currently defined in the `src/components/Tutorial/md-in-js` folder.

For example, the bullet points in the first section are defined here (in Markdown format, within JavaScript files):

https://github.com/microbiomedata/nmdc-field-notes/blob/3673c0b74b0c55af4b3be2ce0da6369330e56bc4/src/components/Tutorial/md-in-js/soilPackage-001.md.ts#L5-L13

And the bullet points in the second section are defined here:

https://github.com/microbiomedata/nmdc-field-notes/blob/3673c0b74b0c55af4b3be2ce0da6369330e56bc4/src/components/Tutorial/md-in-js/soilPackage-002.md.ts#L5-L14

A **_live_** version of the preliminary tutorial screen (implemented via PR #62) is at: https://fieldnotes.microbiomedata.org/tutorial

This issue is a follow-on to #48, which was about designing and implementing the screen.

**Comment by eecavanna** [comment]
Here's an example of a bullet point I think is incomplete:

https://github.com/microbiomedata/nmdc-field-notes/blob/3673c0b74b0c55af4b3be2ce0da6369330e56bc4/src/components/Tutorial/md-in-js/soilPackage-001.md.ts#L10

**Comment by eecavanna** [comment]
Here's an example of two different punctuation styles being used:

https://github.com/microbiomedata/nmdc-field-notes/blob/3673c0b74b0c55af4b3be2ce0da6369330e56bc4/src/components/Tutorial/md-in-js/soilPackage-001.md.ts#L5-L6

> The top one uses parentheses and the bottom one doesn't.

**Comment by eecavanna** [comment]
I think this is in progress (finalizing it based upon the current app functionality, that is).

**Comment by pkalita-lbl** [comment]
Content to add is documented here: https://docs.google.com/document/d/1oe3UzjaoGrHutzn6f-UMhZ1_83SY87FmiM3sa38rgG0/edit

Discussed in June 22 squad meeting and decided that what's currently in that document is good enough to move forward and we'll close this issue now.
