### ISSUE TITLE
Add theme control to Settings page

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#79]
Currently the interface switches between light and dark mode automatically based on system settings. It might be nice to add a control to the Settings page to let the user choose between light, dark, or automatic (based on system settings). See https://ionicframework.com/docs/theming/dark-mode for Ionic's docs on switching modes. Persist the user's choice by expanding the `StoreContext` in `src/Store.tsx`.

**Comment by eecavanna** [comment]
I originally thought about using a light/dark toggle switch, but when I considered giving the user the ability to say "my preference is neither that the app always be light nor always be dark, but that the app do whatever I specify at the OS level," I decided to go with a selector that allows for 3 options. Here's what that looks like on my local machine:

<img width="387" alt="image" src="https://github.com/microbiomedata/nmdc-field-notes/assets/134325062/4f1889f4-4180-48f6-ae37-124c7244143b">
