### ISSUE TITLE
Unable to save changes of sample metadata when save button out of frame

### ISSUE THREAD

**Issue by simroux** [microbiomedata/nmdc-field-notes#84]
Note: this is for after GSP/ ECR :-)

Just something I noticed on my phone, but I can replicate if I reduce the window size on my browser:
 - Open a sample and click on a metadata to modify, one with a long documentation text (e.g. broad-scale environmental context)
 - If the window is too small, the "Cancel" and "Save" buttons are not visible. 
 - To make them visible, one can grad the frame up, but then the frame goes back down as soon as it's released, so I can't click on "save"

Possible solutions:
- Make the frame "stick" when pulling it up
- Put the "Cancel" and "Save" button above the doc ?

Screenshot below is to illustrate what happens when the window is too small (cancel and save out of frame)

![image](https://github.com/microbiomedata/nmdc-field-notes/assets/8889545/2198d612-652b-4b9b-9676-8c00390fd1a2)

**Comment by pkalita-lbl** [comment]
It looks like Ionic doesn't support scrollable sheet modals out of the box. This issue looks like it might have some good workarounds though: https://github.com/ionic-team/ionic-framework/issues/24631

**Comment by simroux** [comment]
Interesting. Note that this may also be an artifact of the Android App currently displaying as part of a browser rather as a "real" app. The documentation from Ionic indicates that sheets "can be swiped or dragged up to become full-screen", but in my case it never becomes full-screen. So anyway, I wanted to document this now while I still remembered it, but we should probably only try to fix it once we have a "proper" Android App display.
