### ISSUE TITLE
Allow user to re-enable screen-specific tour popups via Settings screen

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-field-notes#88]
Add an "About" section to the Settings screen. This section can include the app version number (#86) and a link to view the "using the app" tutorial (not the "working in the field" checklist/tutorial!) again.

**Comment by eecavanna** [comment]
The tutorial screen being referred to here is the one that is currently only accessible from the home screen when logged out.

**Comment by eecavanna** [comment]
I have rolled this task into a ticket that is about implementing the in-app tours: https://github.com/microbiomedata/nmdc-field-notes/issues/133 

I will close this ticket and track the task in that other ticket instead.
